# Target Guided Ordinal Encoding

In [2]:
import pandas as pd

In [6]:
df = pd.DataFrame({
    'city': ['Paris', 'New York', 'Los Angeles', 'Chicago', 'Houston', 'New York'],
    'price': [100, 200, 150, 120, 180, 160]
})
df

          city  price
0        Paris    100
1     New York    200
2  Los Angeles    150
3      Chicago    120
4      Houston    180
5     New York    160

In [8]:
mean_price = df.groupby('city')['price'].mean()

In [9]:
df['city_encoded'] = df['city'].map(mean_price)
df

          city  price  city_encoded
0        Paris    100         100.0
1     New York    200         180.0
2  Los Angeles    150         150.0
3      Chicago    120         120.0
4      Houston    180         180.0
5     New York    160         180.0

In [12]:
df[['price', 'city_encoded']]

   price  city_encoded
0    100         100.0
1    200         180.0
2    150         150.0
3    120         120.0
4    180         180.0
5    160         180.0

In [15]:
import seaborn as sns
df = sns.load_dataset('tips')

In [16]:
mean_bill = df.groupby('time')['total_bill'].mean()

C:\Users\swapn\AppData\Local\Temp\ipykernel_12324\3752496170.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_bill = df.groupby('time')['total_bill'].mean()

In [17]:
df['time_encoded'] = df['time'].map(mean_bill)

In [18]:
df

     total_bill   tip     sex smoker   day    time  size time_encoded
0         16.99  1.01  Female     No   Sun  Dinner     2    20.797159
1         10.34  1.66    Male     No   Sun  Dinner     3    20.797159
2         21.01  3.50    Male     No   Sun  Dinner     3    20.797159
3         23.68  3.31    Male     No   Sun  Dinner     2    20.797159
4         24.59  3.61  Female     No   Sun  Dinner     4    20.797159
..          ...   ...     ...    ...   ...     ...   ...          ...
239       29.03  5.92    Male     No   Sat  Dinner     3    20.797159
240       27.18  2.00  Female    Yes   Sat  Dinner     2    20.797159
241       22.67  2.00    Male    Yes   Sat  Dinner     2    20.797159
242       17.82  1.75    Male     No   Sat  Dinner     2    20.797159
243       18.78  3.00  Female     No  Thur  Dinner     2    20.797159

[244 rows x 8 columns]

In [19]:
df[['total_bill','time_encoded']]

     total_bill time_encoded
0         16.99    20.797159
1         10.34    20.797159
2         21.01    20.797159
3         23.68    20.797159
4         24.59    20.797159
..          ...          ...
239       29.03    20.797159
240       27.18    20.797159
241       22.67    20.797159
242       17.82    20.797159
243       18.78    20.797159

[244 rows x 2 columns]

In [20]:
df.tail(100)

     total_bill   tip     sex smoker   day    time  size time_encoded
144       16.43  2.30  Female     No  Thur   Lunch     2    17.168676
145        8.35  1.50  Female     No  Thur   Lunch     2    17.168676
146       18.64  1.36  Female     No  Thur   Lunch     3    17.168676
147       11.87  1.63  Female     No  Thur   Lunch     2    17.168676
148        9.78  1.73    Male     No  Thur   Lunch     2    17.168676
..          ...   ...     ...    ...   ...     ...   ...          ...
239       29.03  5.92    Male     No   Sat  Dinner     3    20.797159
240       27.18  2.00  Female    Yes   Sat  Dinner     2    20.797159
241       22.67  2.00    Male    Yes   Sat  Dinner     2    20.797159
242       17.82  1.75    Male     No   Sat  Dinner     2    20.797159
243       18.78  3.00  Female     No  Thur  Dinner     2    20.797159

[100 rows x 8 columns]